### ISSUE TITLE
Usage of the replace_token

### ISSUE THREAD

**Issue by Lireanstar** [HaozheZhao/MIC#11]
Hi there,

We found that the following codes are puzzling.

`replace_token="".join(32*[image_palceholder])`

So, why choose the replace_token, and what about the numbers of the image_palceholder (“图”) to be set as 32?

Hope for your kind help!

**Comment by HaozheZhao** [comment]
Hi,
You can refer to the changes in our recent commits regarding the "model" folder. We have successfully achieved parallel data processing in MMICL, specifically for image processing.

MMICL is capable of accepting input in the form of interleaved images and texts. As a result, we need to combine the visual and text embeddings in this interleaved format. Initially, we used an image placeholder to indicate where the image embedding should be inserted. Consequently, this process inevitably requires looping concatenation of variables, which is a linear operation and necessitates extra GPU memory space and computation time. 

Now, we can simply replace the 32-bit image placeholder with the corresponding processed image embedding. This is a parallel operation and does not require additional memory space. We set the number of image placeholders to 32 because the visual tokens generated from the Visual Prompt Generator (Q-former) have a fixed size of 32*768.

**Comment by Lireanstar** [comment]
Many thanks for your response!
