### ISSUE TITLE
Composition of MIC_5M

### ISSUE THREAD

**Issue by henrycjh** [HaozheZhao/MIC#23]
Hi, thanks for your great work! I am curious about the actual composition of the MIC_5M, since the statistic of dataset shown in the paper do not match the number 5M. Below is the table in the paper:
![image](https://github.com/HaozheZhao/MIC/assets/73419275/2d3b7d65-075e-471b-9593-c2e1215cd6a7)

And there is another question about the statistic of dataset. Did you use some method to filter the data you used? I notice that in the first row of the table, you mention that the training set of COCO caption is 566747, but I got 591753 from official website. And same for the LLaVA-Instruct-150K, you only use 15K data out of 150K.
Thanks for your attention!

**Comment by HaozheZhao** [comment]
Hello, 

Thank you for your interest and dedication to our project!

Regarding your inquiries about the data composition and filter strategies, I would recommend looking at this [repository](https://github.com/HaozheZhao/MIC_tool). It provides detailed information on the dataset class for each dataset, demonstrating how we filter and store them as arrow files for training. We also consistently update the MIC dataset – you can consult the [modelscope](ww.modelscope.cn/datasets/BleachNick/MIC) for the most recent data composition (uploading data to Huggingface has proven challenging due to network issues). We plan to include more information on the dataset and update this table in the future edition of our paper.
